{{ .ProjectSnake }}/package.json
{{ .ProjectSnake }}/pnpm-lock.yaml

Reverts aspect-build/aspect-workflows-template#16

Revert "chore(deps): update dependency eslint to v9"

---

.github/workflows/ci.yaml
{{ .ProjectSnake }}/.bazeliskrc

chore(deps): upgrade Aspect CLI

---

.github/workflows/ci.yaml
scaffold.yaml
{{ .ProjectSnake }}/.aspect/cli/config.yaml
{{ .ProjectSnake }}/.eslintrc.cjs
{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/README.bazel.md
{{ .ProjectSnake }}/go.mod
{{ .ProjectSnake }}/tools/format/BUILD.bazel

---
- Breaking change (forces users to change their own code or config): yes
- Suggested release notes appear below: yes
Now offers to setup rules_go.

feat: add Go scaffolding

---

{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/WORKSPACE.bazel
{{ .ProjectSnake }}/tools/format/BUILD.bazel
{{ .ProjectSnake }}/tools/lint/BUILD.bazel
{{ .ProjectSnake }}/tools/lint/linters.bzl

refactor: get ruff from multitool

---

.github/workflows/ci.yaml
{{ .ProjectSnake }}/tools/tools.lock.json
{{ .ProjectSnake }}/tools/yq

Update remaining tool versions to latest releases

chore: add tools/yq

---

scaffold.yaml
{{ .ProjectSnake }}/.aspect/cli/py3_image.star
{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/tools/oci/BUILD.bazel
{{ .ProjectSnake }}/tools/oci/py3_image.bzl

feat: py3_image

---

{{ .ProjectSnake }}/.aspect/cli/config.yaml
{{ .ProjectSnake }}/.aspect/cli/py3_image.star
{{ .ProjectSnake }}/MODULE.bazel

- Searched for relevant documentation and updated as needed: yes/no
- Breaking change (forces users to change their own code or config): yes/no
- Suggested release notes appear below: yes/no

fix: fix py3_image problems

---

.github/workflows/ci.yaml

Java smoke

---

{{ .ProjectSnake }}/README.bazel.md

As part of a general docs and DX polish for "getting started", I took a pass at fixing up the template files. This PR removes a lot of the white space from the generated MD file and also polishes some grammar. 
---

docs: Polish MD template for nicer generated MD file

---

.github/workflows/ci.yaml
scaffold.yaml
{{ .ProjectSnake }}/.aspect/cli/config.yaml
{{ .ProjectSnake }}/.aspect/cli/shell.star
{{ .ProjectSnake }}/.bazeliskrc
{{ .ProjectSnake }}/BUILD.bazel
{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/tools/_run_under_cwd.sh
{{ .ProjectSnake }}/tools/lint/linters.bzl

Move shellcheck feature to be conditional on this new language being selected
---
- Suggested release notes appear below: no

feat: add rules_shell if requested

---

scaffold.yaml
user_stories/py

Based on the lecture: https://www.youtube.com/live/SLQp8U10UMo?feature=shared&t=5431

chore: add python copier story

---

{{ .ProjectSnake }}/BUILD.bazel

The latter term is being phased out FWICT

fix: use repository rather than workspace

---

{{ .ProjectSnake }}/.aspect/cli/shell.star

discovered in recording the 101 bazel course.
More testing would be nice in `user_stories/shell`

fix: trivial starlark bug

---

{{ .ProjectSnake }}/BUILD

chore: generate BUILD instead of BUILD.bazel

---

{{ .ProjectSnake }}/.bazeliskrc
{{ .ProjectSnake }}/BUILD

chore: upgrade aspect-cli to 2025.19.5

---

{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/package.json

Ideally this will be the default, see https://github.com/aspect-build/rules_js/pull/2220
Needed to make my Angular 20 recording go smoothly.

chore(deps): upgrade pnpm

---

{{ .ProjectSnake }}/MODULE.bazel

Needed for `system_library` repo rule

add rules_cc

---

.github/workflows/ci.yaml
scaffold.yaml
user_stories/go
user_stories/py
user_stories/shell
{{ .ProjectSnake }}/BUILD
{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/README.bazel.md
{{ .ProjectSnake }}/tools/repin
{{ .ProjectSnake }}/tools/tools.lock.json

Aspect CLI v2 will make these equivalent, and this removes an objection for using our template in the LF bazel 101 training

refactor: use gazelle rather than aspect configure

---

.github/workflows/deliver.yaml

Auto-populate https://github.com/orgs/bazel-starters/repositories

Push starters

---

{{ .ProjectSnake }}/.vscode/extensions.json
{{ .ProjectSnake }}/.vscode/launch.json
{{ .ProjectSnake }}/.vscode/settings.json

feat: add .vscode

---

{{ .ProjectSnake }}/.devcontainer/Dockerfile
{{ .ProjectSnake }}/.devcontainer/devcontainer.json
{{ .ProjectSnake }}/tools/lint/linters.bzl

Makes a convenient and reliable sandbox for codelab/training courses

chore: configure GH codespaces

---

{{ .ProjectSnake }}/.vscode/settings.json

---
- Searched for relevant documentation and updated as needed: yes/no
- Breaking change (forces users to change their own code or config): yes/no
- Suggested release notes appear below: yes/no

Tell VSCode where to find buildifier from bazel_env

---

{{ .ProjectSnake }}/MODULE.bazel

Green up `main` 😢 🤡
This will hopefully go away when the default gets flipped. FYI @rickeylev

always dep on rules_python

---

{{ .ProjectSnake }}/.vscode/settings.json
{{ .ProjectSnake }}/tools/tools.lock.json

remove some tools that aren't needed yet; see https://github.com/buildbuddy-io/bazel_env.bzl/issues/61
thanks @hofbi for the pointer to https://github.com/hofbi/bazel-ide/

chore: add starpls for vscode

---

scaffold.yaml
user_stories/kotlin.md
{{ .ProjectSnake }}/.aspect/cli/config.yaml
{{ .ProjectSnake }}/.editorconfig
{{ .ProjectSnake }}/BUILD
{{ .ProjectSnake }}/MODULE.bazel
{{ .ProjectSnake }}/ktlint-baseline.xml
{{ .ProjectSnake }}/tools/lint/linters.bzl

When this merges, bazel-starters/kotlin will be auto-updated.
FYI @nkoroste

fix: add ktlint
