{{ .ProjectSnake }}/BUILD.bazel, {{ .ProjectSnake }}/pyproject.toml, {{ .ProjectSnake }}/requirements.txt, {{ .ProjectSnake }}/requirements_lock.txt
The pyproject.toml file can be the input to pip-compile, and removes one boilerplate file.
---
=> chore: remove requirements.txt

{{ .ProjectSnake }}/.aspect/cli/config.yaml, {{ .ProjectSnake }}/BUILD.bazel
- Suggested release notes appear below: yes
When including Python in the languages, sets up BUILD file generation with `aspect configure`
Ran through it locally in a repo generated by `aspect init`
=> feat: include Python BUILD file generation

.github/workflows/ci.yaml, {{ .ProjectSnake }}/BUILD.bazel, {{ .ProjectSnake }}/MODULE.bazel, {{ .ProjectSnake }}/package.json, {{ .ProjectSnake }}/tools/format/BUILD.bazel, {{ .ProjectSnake }}/tools/lint/BUILD.bazel, {{ .ProjectSnake }}/tools/lint/linters.bzl, {{ .ProjectSnake }}/tools/toolchains/BUILD.bazel
It literally took me two hours to get all the hyphens in the right spots to make it remain formatted along every conditional path.
Note that I *could* update to a newer scaffold that has a "post" hook feature, but then every user will observe that format running after stamping it out, so this is better (even if really annoying)
---
=> chore: enable buildifier formatting check

scaffold.yaml, {{ .ProjectSnake }}/BUILD.bazel, {{ .ProjectSnake }}/MODULE.bazel, {{ .ProjectSnake }}/README.bazel.md, {{ .ProjectSnake }}/gazelle_python.yaml
It requires a manifest file to lookup import statements to 3p packages
---
- Suggested release notes appear below: yes
Python projects now support third-party packages in `configure` without needing a manual `resolve` directive.
=> chore: finish setup of python gazelle

README.md
Include the requisite `brew tap` step.
Without this, `brew install scaffold` fails with:
No available formula with the name "scaffold".
Did you mean skaffold?
Ref: https://hay-kot.github.io/scaffold/introduction/quick-start.html#homebrew
=> Fix `brew install scaffold` instructions

{{ .ProjectSnake }}/tools/format/BUILD.bazel
Projects generated with support for Python and linting+formatting are now configured to format Python code out-of-the-box.
---
- Suggested release notes appear above: yes
- Manual testing:
1. Generate a project opting into Python + formatting
2. `echo "'foo'" > foo.py`
3. `git init && git add .`
4. `bazel run //tools/format:format`
* output should include `Formatted Python in 0m0.XYZs`
* `git diff` should show that the single quotes in `foo.py` were changed to double quotes
=> Configure ruff formatting for Python projects

scaffold.yaml, {{ .ProjectSnake }}/.pre-commit-config.yaml
The README.bazel.md that is currently generated mentions the ability to use pre-commit to format code automatically on git commit.
With these changes, a .pre-commit-config.yaml is now generated that configures an 'aspect run format' hook out-of-the-box when users opt into formatting/linting.
---
- Suggested release notes appear below: yes
When generating a new project with linting/formatting enabled, a .pre-commit-config.yaml is now written that configures an `aspect run format` pre-commit hook.
- Manual testing:
1. Run `aspect init`, opting into auto-formatting
2. Run `pre-commit install`
3. `git commit` any file subject to auto-formatting (e.g. …
=> Add 'aspect run format' pre-commit hook.

scaffold.yaml, {{ .ProjectSnake }}/.aspect/cli/config.yaml, {{ .ProjectSnake }}/.aspect/cli/package-json-scripts.star, {{ .ProjectSnake }}/.bazeliskrc
Requires changing the scaffolded project to use the "pro" version of CLI so we can use starzelle plugins.
=> feat: generate js_binary for simple package.json scripts

{{ .ProjectSnake }}/BUILD.bazel
shouldn't be conditional on enabling lint
=> fix: always expose pyproject.toml

.github/workflows/ci.yaml
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> chore: follow GH deprecation instruction

{{ .ProjectSnake }}/.github/workflows/weekly_tag.yaml
If a name isn't set the then GitHub Actions shows the name of the yaml `.github/workflows/weekly_tag.yaml` in the list of workflows. This gives it a nicer name.
=> chore: add name to weekly_tag.yaml GitHub Actions workflow

.github/workflows/ci.yaml, scaffold.yaml, {{ .ProjectSnake }}/Cargo.toml, {{ .ProjectSnake }}/MODULE.bazel, {{ .ProjectSnake }}/README.bazel.md, {{ .ProjectSnake }}/src/main.rs, {{ .ProjectSnake }}/tools/_run_under_cwd.sh, {{ .ProjectSnake }}/tools/cargo, {{ .ProjectSnake }}/tools/format/BUILD.bazel
Goals:
- should be as similar as possible to using Rust outside of Bazel. All non-Bazel tooling should continue to work.
- should be consistent with other languages under Aspect, for example the cargo "repinning" operation ought to appear similar-shaped
=> feat: add Rust support in 'aspect init'

{{ .ProjectSnake }}/tools/oci/py3_image.bzl
- Suggested release notes appear below: no
- Manual testing; please provide instructions so we can reproduce: Tested with @alexeagle manually
=> fix: set runfiles and workdir for py3_image

{{ .ProjectSnake }}/MODULE.bazel
Otherwise I get a warning at the beginning of the demo
=> fix: run 'bazel mod tidy'

{{ .ProjectSnake }}/.github/workflows/weekly_tag.yaml
=> fix: grant repo write permission to weekly tagger

scaffold.yaml
The next steps message suggests that the user run `...`, but this is not a valid target pattern, and results in an error.
---
- Suggested release notes appear below:
Produce correct target pattern syntax in "Next Steps" help message after project creation.
Run the scaffold manually from source.
=> fix: use correct target syntax in next steps messaging

scaffold.yaml, {{ .ProjectSnake }}/REPO.bazel
Should have been in #268 
---
Created a repo and verified Bazel 8 doesn't try to build node_modules
=> feat: ignore node_modules folders

.github/workflows/ci.yaml, user_stories/cpp, user_stories/go, user_stories/java, user_stories/js, user_stories/kitchen-sink, user_stories/minimal, user_stories/py, user_stories/rust, user_stories/shell
=> Convert tests to user stories

{{ .ProjectSnake }}/MODULE.bazel, {{ .ProjectSnake }}/tools/lint/BUILD.bazel
rules_lint doesn't have any linting for Go yet.
Follows https://github.com/bazel-contrib/rules_go/blob/master/docs/go/core/bzlmod.md#configuring-nogo
Also remove the careful whitespace handling markers in lint/BUILD.bazel since we now run buildifier after scaffolding. This makes the file more readable.
=> feat: add nogo as a simple linting option

user_stories/go
Executable version of the exercise we'll do in the training course
---
=> feat: fill in Go developer journey

user_stories/go, {{ .ProjectSnake }}/MODULE.bazel
This demonstrates that `platforms` has to be a Bazel module dep.
---
=> fix: test that OCI containers build

{{ .ProjectSnake }}/tools/oci/py3_image.bzl
A breaking change landed upstream https://github.com/aspect-build/rules_py/commit/b9a2c70a56d80b767102660644b7ce3e69d42e7f
And we picked it up via renovate.
=> fix: py_image generation

scaffold.yaml, {{ .ProjectSnake }}/REPO.bazel
Otherwise a mix of non-bazel activities in a python project will break `...` expansions
Discovered in updating the Bazel 102 course.
Note, this will now *always* create the `REPO.bazel` file, which I think is actually better since that's not a JS specific file it's a bit surprising when you got one of those in your project.
=> fix: ignore pycache folder

scaffold.yaml
It's supposed to be a sibling of `prompt`
The problem tripped someone in the training course today.
=> fix: validation for at least one lang

.github/workflows/ci.yaml
Allows Aspect CLI to upgrade, since we'll have coverage that this template works with both old and new versions.
At some point in the future I'll remove 0.3.0 testing once it "feels" like most users will be on the newer Aspect CLI version.
=> chore: test with most recent scaffold version

{{ .ProjectSnake }}/.aspect/bazelrc/BUILD, {{ .ProjectSnake }}/BUILD, {{ .ProjectSnake }}/tools/BUILD, {{ .ProjectSnake }}/tools/format/BUILD, {{ .ProjectSnake }}/tools/lint/BUILD
We can reduce the conditional logic by placing load statements with the use-site of symbols they load. buildifier will re-order the load statements for us.
Also throw out the whitespace-control hyphens, which aren't load-bearing anymore.
=> refactor: fully rely on buildifier

{{ .ProjectSnake }}/tools/_run_under_cwd.sh, {{ .ProjectSnake }}/tools/go
=> cleanup: remove run_under_cwd

.github/workflows/ci.yaml
Hopefully nearly all users have upgraded their Aspect CLI, or if using scaffold directly they upgraded that.
=> chore: remove old Scaffold version from testing

{{ .ProjectSnake }}/tools/BUILD
Downstreams https://github.com/buildbuddy-io/bazel_env.bzl/pull/58
=> fix: use cargo from upstream_wrapper

{{ .ProjectSnake }}/.devcontainer/devcontainer.json
The non-interactive environment the postCreateCommand runs in doesn't see the direnv install hook
fyi @fmeum
=> ignore exit 1 from bazel_env

scaffold.yaml, {{ .ProjectSnake }}/.bazelrc, {{ .ProjectSnake }}/.pre-commit-config.yaml, {{ .ProjectSnake }}/README.bazel.md, {{ .ProjectSnake }}/githooks/check-config.sh, {{ .ProjectSnake }}/githooks/pre-commit
Means we don't have to ask developers to install a third-party python tool
Follows updated docs at https://github.com/aspect-build/rules_lint/blob/main/docs/formatting.md#install-as-a-pre-commit-hook
=> chore: switch from pre-commit to githooks
